### PR TITLE
Revert "Create a powerful HTML frontend"

### PR DESCRIPTION
**Pull request by RebasedMarine**
Reverts RebasedMarine/crowdsale#2

### CODE REVIEW

**Comment by RebasedMarine** [comment]
Thanks for the fast submission @sebastiantf! Should this work if I open it locally? It gets stuck for me in "loading" when I open it in Chrome (with Metamask connected to Ropsten).

Screenshot 2020-08-09 at 16 38 39

**Comment by RebasedMarine** [comment]
Ah nevermind! It works with SimpleHTTPServer.

**Comment by sebastiantf** [comment]
@sebastiantf It works when you serve the folder with an http server. Something like `lite-server` or `SimpleHTTPServer` like you used should be suitable.

Hope you got it working.

**Comment by RebasedMarine** [comment]
Hey @sebastiantf just to double-check, did you receive the bounty?

**Comment by sebastiantf** [comment]
Yes @RebasedMarine. I got it.

**Pull request merged**
